services:
  - type: web
    name: econ-backend
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    region: frankfurt
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: econ-db
          property: connectionString

databases:
  - name: econ-db
    plan: free